INSERT INTO PUBLIC.CUSTOMER (ID, USERNAME, PASSWORD) VALUES (1,'user', '$2a$10$cn69PcH/PYyKSdvI0oCox.cFrK5fKW9KrX8tfgV3JLo8dDKS/BBtC');
INSERT INTO PUBLIC.CUSTOMER (ID, USERNAME, PASSWORD) VALUES (2,'user2', '$2a$10$NsDPQHYP8QNjBPG5K.U7EOnx6VEpZfNOZE7Bmjxl.E27KxkWddIh6');
